# États du formulaire
WHY, WHAT, LEVEL, NAME, PHONE, COUNTRY, EMAIL, EXPECTATIONS, DISCOVERY= range(9)

CATEGORIE, NOMBRE_QUESTIONS, QUESTION, NB_CHOIX, CHOIX, REPONSE_SUIVANTE = range(6)

ASK_IDS = 0

QUESTION, ANSWER, EXPLANATION, CATEGORIE = range(4)
NOM_CATEGORIE = range(1)
WAITING_ANSWER = range(1)
NOM_CATEGORIE = range(1)
CHOISIR_CATEGORIE = range(1)
ASK_USER_ID  = range(1)
WAITING_ANSWER_1, WAITING_ANSWER_2 = range(2)       