# États du formulaire
WHY, WHAT, LEVEL, NAME, PHONE, COUNTRY, EMAIL, EXPECTATIONS, DISCOVERY= range(9)

CATEGORIE, NOMBRE_QUESTIONS, QUESTION, NB_CHOIX, CHOIX, REPONSE_SUIVANTE = range(6)

ASK_IDS = 0
