# États du formulaire
WHY, WHAT, LEVEL, NAME, PHONE, COUNTRY, EMAIL, EXPECTATIONS, DISCOVERY, DAYS= range(10)

CATEGORIE, NOMBRE_QUESTIONS, QUESTION, NB_CHOIX, CHOIX, REPONSE_SUIVANTE = range(6)

ASK_IDS = 0

GET_MAIL = range(1)

QUESTION, ANSWER, EXPLANATION, CATEGORIE = range(4)
NOM_CATEGORIE = range(1)
WAITING_ANSWER = range(1)
NOM_CATEGORIE = range(1)
CHOISIR_CATEGORIE = range(1)
ASK_USER_ID  = range(1)
WAITING_ANSWER_1, WAITING_ANSWER_2 = range(2)   

LEVEL_WELCOME, WHY_WELCOME, NUMERO_WHATSAPP_WELCOME, MAIL_WELCOME, NOM_WELCOME = range(5)

USER,PWD = range (2)

EMAIL_EXAM = range(1)

WAITING_ANSWER_EXAM =range(1)

NAME_EXAM , ARGS_1, ARGS_2 = range(3)

